## Feature Engineering and Stuff

In [1]:
import pandas as pd
import importlib
import data_proc
import sys
import numpy as np

In [2]:
importlib.reload(data_proc)

In [8]:
df_skaters = data_proc.read_data("~/Desktop/dfs/hockey/", skater=True)

In [13]:
df_skaters.drop('Unnamed: 0', axis=1, inplace=True)

In [14]:
df_skaters.fillna(0, inplace=True)

In [22]:
df_skaters['blocked'] = 0

In [17]:
df_skaters.sort_values(by=['playerId', 'gameDate'], inplace=True)

In [23]:
df_skaters = data_proc.add_fantasy(df_skaters, 'fantasy_points')

In [25]:
feature_list = ['assists', 'goals', 'plusMinus', 'points', 'fantasy_points', 'shootingPct', 'shots']

In [27]:
for feature in feature_list:
    df_skaters[f'{feature}_ma6'] = data_proc.moving_average(df_skaters, feature, 'playerId', 6)
    df_skaters[f'{feature}_ma6'] = df_skaters[f'{feature}_ma6'].shift(1)

In [31]:
for feature in feature_list:
    df_skaters[f'{feature}_ma7'] = data_proc.moving_average(df_skaters, feature, 'playerId', 7)
    df_skaters[f'{feature}_ma7'] = df_skaters[f'{feature}_ma7'].shift(1)
    
for feature in feature_list:
    df_skaters[f'{feature}_ma3'] = data_proc.moving_average(df_skaters, feature, 'playerId', 3)
    df_skaters[f'{feature}_ma3'] = df_skaters[f'{feature}_ma3'].shift(1)
    
for feature in feature_list:
    df_skaters[f'{feature}_last_game'] = df_skaters[feature].shift(1)
    
for feature in feature_list:
    df_skaters[f'{feature}_ma10'] = data_proc.moving_average(df_skaters, feature, 'playerId', 10)
    df_skaters[f'{feature}_ma10'] = df_skaters[f'{feature}_ma10'].shift(1)

for feature in feature_list:
    df_skaters[f'{feature}_ma14'] = data_proc.moving_average(df_skaters, feature, 'playerId', 14)
    df_skaters[f'{feature}_ma14'] = df_skaters[f'{feature}_ma14'].shift(1)

### Data Exploration

In [28]:
df_skaters.columns

Index(['assists', 'evGoals', 'evPoints', 'faceoffWinPct', 'gameDate', 'gameId',
       'gameWinningGoals', 'gamesPlayed', 'goals', 'homeRoad', 'lastName',
       'opponentTeamAbbrev', 'otGoals', 'penaltyMinutes', 'playerId',
       'plusMinus', 'points', 'pointsPerGame', 'positionCode', 'ppGoals',
       'ppPoints', 'shGoals', 'shPoints', 'shootingPct', 'shootsCatches',
       'shots', 'skaterFullName', 'teamAbbrev', 'timeOnIcePerGame', 'blocked',
       'fantasy_points', 'assists_ma6', 'goals_ma6', 'plusMinus_ma6',
       'points_ma6', 'fantasy_points_ma6', 'shootingPct_ma6', 'shots_ma6'],
      dtype='object')

In [33]:
x = df_skaters.corr().sort_values(by='fantasy_points')['fantasy_points']

In [36]:
## shots ma3, fantasy points last game, points ma3

In [37]:
## create regression for individual players

In [38]:
df_skaters['playerId'].value_counts().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of 8471675    12087
8471214    10661
8466138     9093
8462042     8555
8466148     8283
           ...
8480289        2
8480068        2
8476166        2
8478455        2
8472361        1
Name: playerId, Length: 1900, dtype: int64>

In [3]:
df_skaters = pd.read_csv('df_skaters.csv')
df_skaters_misc = pd.read_csv('df_skaters_misc.csv')

In [22]:
df_skaters.set_index(['gameId', 'playerId'], inplace=True)

In [23]:
df_skaters_misc.set_index(['gameId', 'playerId'], inplace=True)

In [24]:
df_j = pd.merge(df_skaters, df_skaters_misc, left_index=True, right_index=True)

In [31]:
df_skaters = df_skaters[~df_skaters.index.duplicated(keep='first')]

In [32]:
df_skaters.shape

(17747, 28)

In [18]:
df_joined.head()

,Unnamed: 0_x,assists,evGoals,evPoints,faceoffWinPct,gameDate_x,gameId,gameWinningGoals,gamesPlayed_x,goals,...,missedShots,opponentTeamAbbrev_y,otGoals_y,positionCode_y,shootsCatches_y,skaterFullName_y,takeaways,takeawaysPer60,teamAbbrev_y,timeOnIcePerGame_y
0,4,1,1,1,0.41666,2022-10-12,2022020010,1,1,3,...,1,VAN,0,C,L,Connor McDavid,0,0.0,EDM,1416.0
1,4,1,1,1,0.41666,2022-10-12,2022020010,1,1,3,...,1,VAN,0,C,L,Connor McDavid,0,0.0,EDM,1416.0
2,4,1,1,1,0.41666,2022-10-12,2022020010,1,1,3,...,1,VAN,0,C,L,Connor McDavid,0,0.0,EDM,1416.0
3,4,1,1,1,0.41666,2022-10-12,2022020010,1,1,3,...,1,VAN,0,C,L,Connor McDavid,0,0.0,EDM,1416.0
4,4,1,1,1,0.41666,2022-10-12,2022020010,1,1,3,...,1,VAN,0,C,L,Connor McDavid,0,0.0,EDM,1416.0

In [25]:
df_j.head()

                     Unnamed: 0_x  assists  evGoals  evPoints  faceoffWinPct  \
gameId     playerId
2008020575 8459640             99        0        2         2            NaN
           8459640             99        0        2         2            NaN
           8459640             99        0        2         2            NaN
           8459640             99        0        2         2            NaN
           8459640             99        0        2         2            NaN

                     gameDate_x  gameWinningGoals  gamesPlayed_x  goals  \
gameId     playerId
2008020575 8459640   2009-01-03                 1              1      2
           8459640   2009-01-03                 1              1      2
           8459640   2009-01-03                 1              1      2
           8459640   2009-01-03                 1              1      2
           8459640   2009-01-03                 1              1      2

                    homeRoad_x  ... missedShots opponentTeamAbbrev_y  \
gameId     playerId             ...
2008020575 8459640           H  ...           1                  NYI
           8459640           H  ...           1                  NYI
           8459640           H  ...           1                  NYI
           8459640           H  ...           1                  NYI
           8459640           H  ...           1                  NYI

                     otGoals_y  positionCode_y  shootsCatches_y  \
gameId     playerId
2008020575 8459640           0               R                R
           8459640           0               R                R
           8459640           0               R                R
           8459640           0               R                R
           8459640           0               R                R

                     skaterFullName_y  takeaways takeawaysPer60  teamAbbrev_y  \
gameId     playerId
2008020575 8459640         Mike Grier          0            0.0           SJS
           8459640         Mike Grier          0            0.0           SJS
           8459640         Mike Grier          0            0.0           SJS
           8459640         Mike Grier          0            0.0           SJS
           8459640         Mike Grier          0            0.0           SJS

                     timeOnIcePerGame_y
gameId     playerId
2008020575 8459640                940.0
           8459640                940.0
           8459640                940.0
           8459640                940.0
           8459640                940.0

[5 rows x 57 columns]

In [33]:
df_skaters2 = pd.read_csv('df_skaters.csv')

In [38]:
df_skaters2.duplicated().value_counts()

False    866145
True      47595
dtype: int64

In [39]:
df_skaters = df_skaters2[~df_skaters2.duplicated(keep='first')]

In [48]:
df_skaters[['gameId', 'playerId', 'gameDate', 'opponentTeamAbbrev', 'gamesPlayed', 'timeOnIcePerGame', 'goals', 'shots', 'assists']].duplicated().value_counts()

True     848398
False     17747
dtype: int64

In [49]:
df_skaters = pd.read_csv('df_skaters.csv')

In [50]:
df_skaters.shape

(1477568, 30)

In [51]:
df_skaters.duplicated().value_counts()

False    1450106
True       27462
dtype: int64

In [54]:
df_skaters[['gameId', 'playerId', 'gameDate', 'opponentTeamAbbrev', 'gamesPlayed', 'timeOnIcePerGame', 'goals', 'shots', 'assists']].duplicated().value_counts()

True     1448881
False      28687
dtype: int64

In [58]:
x = list(df_skaters.columns)

In [62]:
df_skaters3 = df_skaters[~df_skaters.duplicated(keep='first')]

In [64]:
df_skaters3.shape

(1450106, 30)

In [69]:
df_skaters3.sort_values('gameId').head(20)

,Unnamed: 0,assists,evGoals,evPoints,faceoffWinPct,gameDate,gameId,gameWinningGoals,gamesPlayed,goals,...,ppGoals,ppPoints,shGoals,shPoints,shootingPct,shootsCatches,shots,skaterFullName,teamAbbrev,timeOnIcePerGame
963455,95,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1448220,62,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1154700,82,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1110603,85,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1360248,68,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1066488,88,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1007630,92,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1198779,79,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1374915,67,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
904513,99,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1477528,60,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1286883,73,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1095900,86,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1022349,91,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1404243,65,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
978183,94,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1272204,74,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1418904,64,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1169395,81,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0
1257523,75,0,2,2,0.0,2000-01-01,1999020522,0,1,2,...,0,0,0,0,1.0,R,2,Jason Allison,BOS,1228.0